name: ui-tests

on:
  push:

env:
  AUTOHOTKEY_VERSION: 2.0.19
  WT_VERSION: 1.22.11141.0
  WIN32_OPENSSH_VERSION: 9.8.3.0p2-Preview

jobs:
  ui-tests:
    strategy:
      fail-fast: false
      matrix:
        # Corresponds to Windows Server versions
        # See https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        os: [windows-2025]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache/restore@v4
        id: restore-ahk
        with:
          key: ahk-${{ env.AUTOHOTKEY_VERSION }}
          path: ${{ runner.temp }}/ahk.zip
      - name: Download AutoHotKey2
        if: steps.restore-ahk.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L -o "$RUNNER_TEMP/ahk.zip" \
            https://github.com/AutoHotkey/AutoHotkey/releases/download/v$AUTOHOTKEY_VERSION/AutoHotkey_$AUTOHOTKEY_VERSION.zip
      - uses: actions/cache/save@v4
        if: steps.restore-ahk.outputs.cache-hit != 'true'
        with:
          key: ahk-${{ env.AUTOHOTKEY_VERSION }}
          path: ${{ runner.temp }}/ahk.zip
      - name: Install AutoHotKey2
        shell: bash
        run: |
          mkdir -p "$RUNNER_TEMP/ahk" &&
          "$WINDIR/system32/tar.exe" -C "$RUNNER_TEMP/ahk" -xf "$RUNNER_TEMP/ahk.zip" &&
          cygpath -aw "$RUNNER_TEMP/ahk" >>$GITHUB_PATH

      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            ui-tests
      - name: Minimize existing Log window
        working-directory: ui-tests
        run: |
          $exitCode = 0
          type minimize-log-window.ahk
          & "${env:RUNNER_TEMP}\ahk\AutoHotKey64.exe" /ErrorStdOut /force minimize-log-window.ahk "$PWD\minimize-log-window" 2>&1 | Out-Default
          if (!$?) { $exitCode = 1; echo "::error::Failed to minimize Log window!" } else { echo "::notice::Minimized Log window" }
          exit $exitCode
      - name: Take screenshot
        id: take-screenshot
        if: always()
        shell: powershell
        run: |
          Add-Type -TypeDefinition @"
          using System;
          using System.Runtime.InteropServices;

          public class DpiHelper {
              [DllImport("user32.dll")]
              public static extern bool SetProcessDpiAwarenessContext(IntPtr dpiContext);

              [DllImport("Shcore.dll")]
              public static extern int GetDpiForMonitor(IntPtr hmonitor, int dpiType, out uint dpiX, out uint dpiY);

              [DllImport("User32.dll")]
              public static extern IntPtr MonitorFromPoint(System.Drawing.Point pt, uint dwFlags);

              [DllImport("user32.dll")]
              public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);

              public static uint GetDPI() {
                  // DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 = -4
                  SetProcessDpiAwarenessContext((IntPtr)(-4));

                  uint dpiX, dpiY;
                  IntPtr monitor = MonitorFromPoint(new System.Drawing.Point(0, 0), 2); // MONITOR_DEFAULTTONEAREST
                  GetDpiForMonitor(monitor, 0, out dpiX, out dpiY); // MDT_EFFECTIVE_DPI
                  return (dpiX + dpiY) / 2;
              }
          }
          "@ -ReferencedAssemblies "System.Drawing.dll"

          # First, minimize the Console window in which this script is running
          $hwnd = (Get-Process -Id $PID).MainWindowHandle
          $SW_MINIMIZE = 6

          [DpiHelper]::ShowWindow($hwnd, $SW_MINIMIZE)

          # Now, get the DPI
          $dpi = [DpiHelper]::GetDPI()

          # This function takes a screenshot and saves it as a PNG file
          [Reflection.Assembly]::LoadWithPartialName("System.Drawing")
          function screenshot([Drawing.Rectangle]$bounds, $path) {
            $bmp = New-Object Drawing.Bitmap $bounds.width, $bounds.height
            $graphics = [Drawing.Graphics]::FromImage($bmp)
            $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.size)
            $bmp.Save($path)
            $graphics.Dispose()
            $bmp.Dispose()
          }
          Add-Type -AssemblyName System.Windows.Forms
          $screen = [System.Windows.Forms.Screen]::PrimaryScreen
          $bounds = [Drawing.Rectangle]::FromLTRB(0, 0, $screen.Bounds.Width * $dpi / 96, $screen.Bounds.Height * $dpi / 96)
          screenshot $bounds "ui-tests/screenshot.png"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-tests-${{ matrix.os }}
          path: ui-tests
